server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prism030
    username: root
  data:
    mongodb:
      host: localhost
      port: 27017
      database: prism030
      # mongodb需在admin数据库手动增加管理员用户密码及角色
      # uri: mongodb://localhost:27017/prism030


