server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prism030
    username: root
  rabbitmq:
    host: 123.60.104.150
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      host: 124.223.39.48
      port: 3307
      database: prism030
      username: root
      password: se3
      authentication-database: admin
      # mongodb需在admin数据库手动增加管理员用户密码及角色
      # uri: mongodb://localhost:27017/prism030




