server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prism030
    username: root
    password: 123456
  elasticsearch:
    uris: http://127.0.0.1:9200

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.seciii.prism030.core.pojo.po
  mapper-locations: classpath:mapper/*.xml

