server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prism063
    username: root
    password: 123456

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.seciii.prism063.core.pojo.po
  mapper-locations: classpath:mapper/*.xml

