server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://124.223.39.48:3306/prism030?serverTimezone=Asia/Shanghai
    username: se3
    password: se3

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.seciii.prism030.core.pojo.po
  mapper-locations: classpath:mapper/*.xml

