server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost/prism030?serverTimezone=Asia/Shanghai
    username: iloveyou
    password: iloveyou
  data:
    mongodb:
      host: localhost
      port: 3307
      database: prism030
      # mongodb需在admin数据库手动增加管理员用户密码及角色
      username: iloveyou
      password: iloveyou
      authentication-database: admin
#      uri: mongodb://localhost:27017/prism030

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.seciii.prism030.core.pojo.po
  mapper-locations: classpath:mapper/*.xml

