spring:
  datasource:
    url: jdbc:mysql://url:port/db
    username: username
  neo4j:
    uri: uri
    authentication:
      username: username
      password: password

  profiles:
    active: prod # 在此选择需要的环境配置文件

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.seciii.prism030.core.pojo.po
  mapper-locations: classpath:mapper/*.xml


segment:
  baseurl: http://ip:port

spark:
  apikey: apikey
  apisecret: apisecret
  appid: appid