spring:
  profiles:
    active: dev # 在此选择需要的环境配置文件

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.seciii.prism030.core.pojo.po
  mapper-locations: classpath:mapper/*.xml