server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prism030
    username: root
  data:
    mongodb:
      host: 124.223.39.48
      port: 3307
      database: prism030
      # mongodb需在admin数据库手动增加管理员用户密码及角色
      username: root
      password: se3
      authentication-database: admin
#      uri: mongodb://localhost:27017/prism030
  neo4j:
    uri:
    authentication:
      username: neo4j
      password:


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.seciii.prism030.core.pojo.po
  mapper-locations: classpath:mapper/*.xml

